HomeWebLesson9/urls.py
from django.contrib import admin
from django.urls import path
from main.views import CityListView1, CityListView2, CityDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oneway/', CityListView1.as_view(), name="list"),
    path('twoway/', CityListView2.as_view(), name="list"),
    path('twoway/<int:pk>', CityDetailView.as_view(), name="detail"),
]

main/models.py
from django.db import models


class CountryCode(models.Model):
    code = models.CharField("Country Code", max_length=2)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = "CC"
        verbose_name_plural = "CCs"


class City(models.Model):
    country_code = models.ForeignKey(CountryCode, on_delete=models.CASCADE)
    ascii_city_name = models.CharField("Ascii name", max_length=128)
    city_name = models.CharField("Name", max_length=128)
    region = models.CharField("Region", max_length=2)
    population = models.IntegerField("pop")
    latitude = models.FloatField("latitude")
    longitude = models.FloatField("longitude")

    def __str__(self):
        return self.city_name

    class Meta:
        verbose_name = "City"
        verbose_name_plural = "Cities"

main/views.py
from django.views.generic import ListView, DetailView
from .models import City


class CityListView1(ListView):
    template_name = "list1.html"
    model = City
    paginate_by = 100

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CityListView2(ListView):
    template_name = "list2.html"
    model = City
    paginate_by = 100

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CityDetailView(DetailView):
    template_name = "detail.html"
    model = City

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}{% endblock %}
</head>
<body>

{% block content %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "css/detail.css" %}">{% endblock %}

{% block title %}Город{% endblock %}

{% block content %}
    <table class="table">
        <tbody>
        <tr>
            <th scope="col">1</th>
            <th scope="col">Country Code</th>
            <td>{{ city.country_code }}</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <th scope="col">ASCII City Name</th>
            <td>{{ city.ascii_city_name }}</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <th scope="col">City Name</th>
            <td>{{ city.city_name }}</td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <th scope="col">Region</th>
            <td>{{ city.region }}</td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <th scope="col">Population</th>
            <td>{{ city.population }}</td>
        </tr>
        <tr>
            <th scope="row">6</th>
            <th scope="col">Latitude</th>
            <td>{{ city.latitude }}</td>
        </tr>
        <tr>
            <th scope="row">7</th>
            <th scope="col">Longitude</th>
            <td>{{ city.longitude }}</td>
        </tr>

        </tbody>
    </table>

{% endblock %}

templates/list1.html
{% extends "base.html" %}

{% block head %}{% endblock %}

{% block title %}Города{% endblock %}

{% block content %}

    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Country Code</th>
            <th scope="col">ASCII City Name</th>
            <th scope="col">City Name</th>
            <th scope="col">Region</th>
            <th scope="col">Population</th>
            <th scope="col">Latitude</th>
            <th scope="col">Longitude</th>
        </tr>
        </thead>
        <tbody>
        {% for city in city_list %}
            <tr>
                <th scope="row">{{ city.id }}</th>
                <td>{{ city.country_code }}</td>
                <td>{{ city.ascii_city_name }}</td>
                <td>{{ city.city_name }}</td>
                <td>{{ city.region }}</td>
                <td>{{ city.population }}</td>
                <td>{{ city.latitude }}</td>
                <td>{{ city.longitude }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav>
        <ul class="pagination" style="margin-top: 5%">
            <div class="btn-group" role="group" aria-label="Basic example" style="margin-top: 5%; margin: 0 auto;">

                <li class="page-item">
                    <a class="btn btn-secondary"
                       {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>

                </li>

                <button type="button" class="btn btn-secondary">
                    <li class="page-item" style="text-align: center;">{{ page_obj.number }}</li>
                </button>

                <li class="page-item">

                    <a class="btn btn-secondary"
                       {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>

            </div>
        </ul>
    </nav>

{% endblock %}

templates/list2.html
{% extends "base.html" %}

{% block head %}{% endblock %}

{% block title %}Города{% endblock %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
        </tr>
        </thead>
        <tbody>
        {% for city in city_list %}
            <tr>
                <th scope="row">{{ city.id }}</th>
                <td><a href="{% url "detail" city.pk %}">{{ city.city_name }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <nav>
        <ul class="pagination" style="margin-top: 5%">
            <div class="btn-group" role="group" aria-label="Basic example" style="margin-top: 5%; margin: 0 auto;">

                <li class="page-item">
                    <a class="btn btn-secondary"
                       {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>

                </li>

                <button type="button" class="btn btn-secondary">
                    <li class="page-item" style="text-align: center;">{{ page_obj.number }}</li>
                </button>

                <li class="page-item">

                    <a class="btn btn-secondary"
                       {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>

            </div>


        </ul>
    </nav>

{% endblock %}